### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by chuckcaley** [mriscoc/Ender3S1-Standard#14]
I have installed the firmware on my s1 but when i go to print anything it just sits there saying heating noozle. I have left it for over 10mins but it still just sits there doing nothing

**Comment by mriscoc** [comment]
If you can print with the original firmware then, you should also be able to print with this. I didn't receive any other report about this issue.

**Comment by ipodtouchdude** [comment]
Try doing a Hotend PID, as I found the default settings for the hotend didn't work. Once I did a hotend PID my hotend heated up quick and accurate.

**Comment by mriscoc** [comment]
Creality didn't publish the source of his firmware, I don't have the official values.
