### ISSUE TITLE
Auto Home correct?

### ISSUE THREAD

**Issue by mrarzt** [mriscoc/Ender3S1-Standard#16]
Hello,

thank you and sorry that i bother you but i don‘t get the first layer consistent. In each corner it looks different.

If i use Auto Home i mentioned that i think it is not exact centered? Is this because this custom firmware have another Build volume like the original? What should happen with Auto Home? Nozzle centered or CR Touch?

I see that the distance at the ABL probing is different to the front edge or back edge.

Best

**Comment by gurbina93** [comment]
Same here, it's not centered. It's off in the X axis by 1cm or so. 
The CR Touch should be the one centered if I'm not mistaken. You can tweak those settings in S1 console. Managed to get within a few mm off the center. But now the first line every gcode start script has before printing goes off the bed which doesn't bother me much.

Bed size is 235mm, but "print area" is 220mm. Not sure if one of these parameters is off.

**Comment by mrarzt** [comment]
My bed level looks like this but as i wrote i think maybe the ABL checks not the correct points? Manual leveling seems not to work because if i set Z to 0 and offset to 0 there is too much space between the steel sheet and the nozzle. I have there 15mm silicon spacer.

This should can be handled from the ABL or?:

![meshview](https://user-images.githubusercontent.com/77169191/152331969-9d95ccf8-3609-41ca-8e02-04e7be0c4808.png)
![octoprint_firstlayer](https://user-images.githubusercontent.com/77169191/152331980-bf040d38-abbc-43fe-9e80-8a43bac3c7f7.png)

Here is my custom start Gcode.
M413 S0 ; Disable Power loss recovery
M190 S{first_layer_bed_temperature[0]} ; set final bed temp
G28 ;Home
G29 ;ABL
M420 S1 ;enable ABL to get sure
M500 ;save bed level
;*** Start Preheating ***
G1 X8.0 Y15 Z30.0 F5000.0 ;No blob on Heatbed
M109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize
;*** End Preheating ***
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G1 X12.0 Y60 Z0.28 F5000.0 ;Move to start position
G1 X12.0 Y190.0 Z0.28 F1500.0 E15 ;Draw the first line
G1 X14.0 Y190.0 Z0.28 F5000.0 ;Move to side a little
G1 X14.0 Y40 Z0.28 F1500.0 E30 ;Draw the second line
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up

EDIT: Here a example. All boxes are printed with the same OFFSET. I use the prusa Steel sheet because i like it so please "ignore" it is the ender3 s1 ;-)

![example-print](https://user-images.githubusercontent.com/77169191/152352064-8f7e72a7-cc43-4f91-98c6-325b549758de.png)

**Comment by JeroenR123** [comment]
I have an identical problem, maby probe offset?

**Comment by JeroenR123** [comment]
> I have an identical problem, maby probe offset?

Just measured, not the case
