### ISSUE TITLE
Default Ender 3 S1 Motion and Retract MM

### ISSUE THREAD

**Issue by ipodtouchdude** [mriscoc/Ender3S1-Standard#6]
Max Speed
300
300
5
25

Acceleration
500
500
100
1000

Jerk
5
5
0.3
5

Steps
80
80
400
424.9

Retract mm 0.8

**Comment by mriscoc** [comment]
Thank you, the next configuration files will have similar values. You can reduce the speed and acceleration in Control/Motion menu or in the g-code start script of your slicer.
