### ISSUE TITLE
Enabling linear advance

### ISSUE THREAD

**Issue by Benisy** [mriscoc/Ender3S1-Standard#7]
Hi. 
I see that in the file `Configuration_adv.h` the value 

> #define LIN_ADVANCE

 is commented out.

I want to know if this is done on purpose or I can enable this parameter. If I enable it, can I change the value of 

> #define LIN_ADVANCE_K

 on the screen? 

Linear Pressure Control is a very useful feature that makes models more correctly shaped, it is strange that you have not included this parameter.

**Comment by mriscoc** [comment]
See here: https://github.com/mriscoc/Ender3S1/issues/2

**Comment by Benisy** [comment]
Found a manual for Creality 4.2.2 boards, need enthusiasts to try it out 😄 

[Linear Advance Modification for Creality 4.2.2 boards v2.pdf](https://github.com/mriscoc/Ender3S1/files/7982699/Linear.Advance.Modification.for.Creality.4.2.2.boards.v2.pdf)

**Comment by mriscoc** [comment]
The S1 has another control board

**Comment by skilly00** [comment]
if you find a way with the new board I'd be open to the mod if it doesn't take my printer out for weeks.  Sounds like the software is the hard part though from your PDF @Benisy and I'm sure it would be the same with the S1s board.
