### ISSUE TITLE
Stop doesn't return control back to home

### ISSUE THREAD

**Issue by hoonu** [mriscoc/Ender3S1-Standard#8]

**Comment by mriscoc** [comment]
Could be related to this? https://github.com/OctoPrint/OctoPrint/issues/4368

**Comment by hoonu** [comment]
I don't believe so as my usage is different. I'm using octoprint and when canceling from the printer console, the UI is unresponsive and I have to keep clicking the wheel to get the full menu back up.

**Comment by mriscoc** [comment]
Disconnect Octoprint, and try. That is a knew issue and will be corrected in Octoprint 1.8.0

**Comment by hoonu** [comment]
I can confirm this was an octoprint issue and works normally from the SD card.
